# Generated by Django 4.2.9 on 2024-01-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('valorUnit', models.IntegerField(default=1)),
                ('qntEstoque', models.IntegerField(default=1)),
                ('nomeProduto', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=15)),
                ('subCategoria', models.CharField(max_length=15)),
                ('marcaProduto', models.CharField(max_length=15)),
            ],
        ),
    ]
