# Generated by Django 4.2.9 on 2024-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='valorUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
