# Generated by Django 4.2.9 on 2024-01-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_alter_produtos_valorunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
