# Generated by Django 4.2.9 on 2024-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='dataEntrada',
            field=models.DateField(default='2024-01-28'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='dataSaida',
            field=models.DateField(default='2024-01-28'),
        ),
    ]
