# Generated by Django 4.2.9 on 2024-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0006_alter_produtos_dataentrada_alter_produtos_datasaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='dataEntrada',
            field=models.DateField(default='2024-01-28'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dataSaida',
            field=models.DateField(default='2024-01-28'),
        ),
    ]
