# Generated by Django 4.2.9 on 2024-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0007_alter_produtos_dataentrada_alter_produtos_datasaida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='dataEntrada',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='dataSaida',
        ),
    ]
