# Generated by Django 4.2.9 on 2024-01-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0008_remove_produtos_dataentrada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
