# Generated by Django 4.2.9 on 2024-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produtos', '0011_delete_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
