# Generated by Django 4.2.9 on 2024-01-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
