# Generated by Django 4.2.9 on 2024-02-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
