# Generated by Django 4.2.9 on 2024-02-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0018_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(max_length=30)),
                ('valorUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qntEstoque', models.IntegerField(default=1)),
                ('categoria', models.CharField(max_length=15)),
                ('subCategoria', models.CharField(max_length=15)),
                ('marcaProduto', models.CharField(max_length=15)),
                ('idFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.fornecedor')),
            ],
        ),
    ]
