# Generated by Django 4.2.9 on 2024-02-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0001_initial'),
        ('Produtos', '0019_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='idFornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fornecedores.fornecedor'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
