# Generated by Django 4.2.9 on 2024-07-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transacao', '0001_initial'),
        ('Produtos', '0020_alter_produtos_idfornecedor_delete_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='idTransacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transacao.transacao'),
        ),
    ]
