# Generated by Django 4.2.7 on 2023-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nivelDeAcesso', models.IntegerField(max_length=1)),
                ('nomeFuncionario', models.CharField(max_length=30)),
                ('enderecoFuncionario', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=11)),
                ('CEP', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
                ('funcao', models.CharField(max_length=30)),
            ],
        ),
    ]
