# Generated by Django 4.2.9 on 2024-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CRUDfuncionario', '0008_remove_funcionario_nomefuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='funcionario_groups', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='funcionario_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
