# Generated by Django 4.2.9 on 2024-01-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0010_rename_idfuncionario_funcionario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='id',
            new_name='idFuncionario',
        ),
    ]
