# Generated by Django 4.2.9 on 2024-01-24 23:29

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0011_rename_id_funcionario_idfuncionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='CPF',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=cpf_field.models.CPFField(default='000.000.000-0', max_length=14, verbose_name='cpf'),
        ),
    ]
