# Generated by Django 4.2.9 on 2024-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0012_remove_funcionario_cpf_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default='daniel@gmail.com', max_length=254, unique=True),
        ),
    ]
