# Generated by Django 4.2.9 on 2024-02-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0013_alter_funcionario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
