# Generated by Django 4.2.9 on 2024-02-28 16:11

import cpf_field.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0014_rename_cpf_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=cpf_field.models.CPFField(default='000.000.000-0', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default='daniel@gmail.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Insira um endereco de email valído')]),
        ),
    ]
