# Generated by Django 4.2.9 on 2024-02-28 16:34

import CRUDfuncionario.validators
import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0015_alter_funcionario_cpf_alter_funcionario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=cpf_field.models.CPFField(default='000.000.000-0', max_length=14, validators=[CRUDfuncionario.validators.valida_cpf], verbose_name='CPF'),
        ),
    ]
