# Generated by Django 4.2.9 on 2024-02-28 17:26

import CRUDfuncionario.validators
import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0016_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=cpf_field.models.CPFField(default='000.000.000-0', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True, validators=[CRUDfuncionario.validators.valida_texto]),
        ),
    ]
