# Generated by Django 4.2.9 on 2024-02-28 18:34

import CRUDfuncionario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0017_alter_funcionario_cpf_alter_funcionario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CEP',
            field=models.CharField(max_length=8, validators=[CRUDfuncionario.validators.valida_cep]),
        ),
    ]
