# Generated by Django 4.2.9 on 2024-07-03 01:40

import CRUDfuncionario.validators
import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0019_alter_funcionario_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=cpf_field.models.CPFField(default='000.000.000-0', max_length=14, validators=[CRUDfuncionario.validators.valida_cpf], verbose_name='CPF'),
        ),
    ]
