# Generated by Django 4.2.9 on 2024-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('idFornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nomeFornecedor', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
