# Generated by Django 4.2.9 on 2024-02-28 19:14

import CRUDfuncionario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[CRUDfuncionario.validators.valida_cnpj]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nomeFornecedor',
            field=models.CharField(max_length=30, validators=[CRUDfuncionario.validators.valida_texto]),
        ),
    ]
