# Generated by Django 4.2.9 on 2024-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0002_alter_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
