# Generated by Django 4.2.9 on 2024-07-27 18:50

import CRUDfuncionario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0003_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nomeFornecedor',
            field=models.CharField(max_length=30, unique=True, validators=[CRUDfuncionario.validators.valida_texto]),
        ),
    ]
