# Generated by Django 4.2.9 on 2024-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRUDfuncionario', '0002_delete_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nivelDeAcesso', models.IntegerField()),
                ('nomeFuncionario', models.CharField(max_length=30)),
                ('enderecoFuncionario', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=11)),
                ('CEP', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
                ('funcao', models.CharField(max_length=30)),
            ],
        ),
    ]
