# Generated by Django 4.2.9 on 2024-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionario', '0006_alter_funcionario_options_alter_funcionario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nivelDeAcesso',
            field=models.IntegerField(default=1),
        ),
    ]
