# Generated by Django 4.2.9 on 2024-07-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0003_alter_fornecedor_cnpj'),
        ('Transacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='idFornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Fornecedores.fornecedor'),
        ),
    ]
