# Generated by Django 4.2.9 on 2024-07-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacao', '0002_transacao_idfornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='horaTransacao',
            field=models.TimeField(default='00:01:02'),
        ),
    ]
